FROM ubuntu:14.04
MAINTAINER Vladimir Prokhoda <vladimirbright@gmail.com>
USER root
RUN apt-get -qq update
RUN apt-get -qq upgrade
RUN locale-gen ru_RU.UTF-8
RUN locale-gen en_US.UTF-8
RUN update-locale LANG=ru_RU.UTF-8 LC_ALL=ru_RU.UTF-8
RUN apt-get -qqy install postgresql
RUN echo "listen_addresses = '*'" >> /etc/postgresql/9.3/main/postgresql.conf
RUN echo "host  all  all  0.0.0.0/0  trust" > /etc/postgresql/9.3/main/pg_hba.conf
USER postgres
CMD /usr/lib/postgresql/9.3/bin/postgres -D /var/lib/postgresql/9.3/main -c config_file=/etc/postgresql/9.3/main/postgresql.conf
